force-app/main/default/objects/datamask__Masking_Execution_Log__c/fields/datamask__Configuration_Name__c.field-meta.xml
<CustomField>
    <fullName>datamask__Configuration_Name__c</fullName>
    <label>Configuration Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/datamask__Masking_Execution_Log__c/fields/Sandbox_Org_ID__c.field-meta.xml
<CustomField>
    <fullName>Sandbox_Org_ID__c</fullName>
    <defaultValue>$Organization.Id</defaultValue>
    <label>Sandbox Org ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/datamask_Masking_Execution_Log_c__x/datamask_Masking_Execution_Log_c__x.object-meta.xml
<CustomObject>
    <externalDataSource>Prod</externalDataSource>
    <externalName>datamask__Masking_Execution_Log__c</externalName>
    <label>Run Log</label>
    <pluralLabel>Run Logs</pluralLabel>
</CustomObject>

force-app/main/default/objects/datamask_Masking_Execution_Log_c__x/fields/datamask_Configuration_Id_c__c.field-meta.xml
<CustomField>
    <fullName>datamask_Configuration_Id_c__c</fullName>
    <externalDeveloperName>datamask__Configuration_Id__c</externalDeveloperName>
    <label>Configuration Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/datamask_Masking_Execution_Log_c__x/fields/datamask_Configuration_Name_c__c.field-meta.xml
<CustomField>
    <fullName>datamask_Configuration_Name_c__c</fullName>
    <externalDeveloperName>datamask__Configuration_Name__c</externalDeveloperName>
    <label>Configuration Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/datamask_Masking_Execution_Log_c__x/fields/datamask_Error_Message_c__c.field-meta.xml
<CustomField>
    <fullName>datamask_Error_Message_c__c</fullName>
    <externalDeveloperName>datamask__Error_Message__c</externalDeveloperName>
    <label>Error Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/datamask_Masking_Execution_Log_c__x/fields/datamask_Has_Master_c__c.field-meta.xml
<CustomField>
    <fullName>datamask_Has_Master_c__c</fullName>
    <defaultValue>false</defaultValue>
    <externalDeveloperName>datamask__Has_Master__c</externalDeveloperName>
    <label>Has Master</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/datamask_Masking_Execution_Log_c__x/fields/datamask_Masking_Execution_Id_c__c.field-meta.xml
<CustomField>
    <fullName>datamask_Masking_Execution_Id_c__c</fullName>
    <externalDeveloperName>datamask__Masking_Execution_Id__c</externalDeveloperName>
    <label>Masking Execution Id</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/datamask_Masking_Execution_Log_c__x/fields/datamask_Message_c__c.field-meta.xml
<CustomField>
    <fullName>datamask_Message_c__c</fullName>
    <externalDeveloperName>datamask__Message__c</externalDeveloperName>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/datamask_Masking_Execution_Log_c__x/fields/datamask_Object_Processing_c__c.field-meta.xml
<CustomField>
    <fullName>datamask_Object_Processing_c__c</fullName>
    <externalDeveloperName>datamask__Object_Processing__c</externalDeveloperName>
    <label>Object Processing</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/datamask_Masking_Execution_Log_c__x/fields/datamask_Record_Count_Total_c__c.field-meta.xml
<CustomField>
    <fullName>datamask_Record_Count_Total_c__c</fullName>
    <externalDeveloperName>datamask__Record_Count_Total__c</externalDeveloperName>
    <inlineHelpText>The total number of records on the object being processed.</inlineHelpText>
    <label>Record Count Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/datamask_Masking_Execution_Log_c__x/fields/datamask_Records_Failed_c__c.field-meta.xml
<CustomField>
    <fullName>datamask_Records_Failed_c__c</fullName>
    <externalDeveloperName>datamask__Records_Failed__c</externalDeveloperName>
    <inlineHelpText>Total number of records failed for this object.</inlineHelpText>
    <label>Records Failed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/datamask_Masking_Execution_Log_c__x/fields/datamask_Records_Processed_c__c.field-meta.xml
<CustomField>
    <fullName>datamask_Records_Processed_c__c</fullName>
    <externalDeveloperName>datamask__Records_Processed__c</externalDeveloperName>
    <inlineHelpText>Total number of records processed for this object.</inlineHelpText>
    <label>Records Processed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/datamask_Masking_Execution_Log_c__x/fields/datamask_Status_c__c.field-meta.xml
<CustomField>
    <fullName>datamask_Status_c__c</fullName>
    <externalDeveloperName>datamask__Status__c</externalDeveloperName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/datamask_Masking_Execution_Log_c__x/fields/datamask_Type_c__c.field-meta.xml
<CustomField>
    <fullName>datamask_Type_c__c</fullName>
    <externalDeveloperName>datamask__Type__c</externalDeveloperName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Execution Start</fullName>
            </value>
            <value>
                <fullName>Pre-Processing Completion</fullName>
            </value>
            <value>
                <fullName>Object Completion</fullName>
            </value>
            <value>
                <fullName>Post-Processing Completion</fullName>
            </value>
            <value>
                <fullName>Execution Completion</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/datamask_Masking_Execution_Log_c__x/fields/External_Id_c__c.field-meta.xml
<CustomField>
    <fullName>External_Id_c__c</fullName>
    <externalDeveloperName>External_Id__c</externalDeveloperName>
    <label>External Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/datamask_Masking_Execution_Log_c__x/fields/Original_Created_Date_c__c.field-meta.xml
<CustomField>
    <fullName>Original_Created_Date_c__c</fullName>
    <externalDeveloperName>Original_Created_Date__c</externalDeveloperName>
    <label>Original Created Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/datamask_Masking_Execution_Log_c__x/fields/Sandbox_Name_c__c.field-meta.xml
<CustomField>
    <fullName>Sandbox_Name_c__c</fullName>
    <externalDeveloperName>Sandbox_Name__c</externalDeveloperName>
    <label>Sandbox Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/datamask_Masking_Execution_Log_c__x/fields/Sandbox_Org_ID_c__c.field-meta.xml
<CustomField>
    <fullName>Sandbox_Org_ID_c__c</fullName>
    <externalDeveloperName>Sandbox_Org_ID__c</externalDeveloperName>
    <label>Sandbox Org ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SyncDataMaskRunLogstoPRDHandler.cls
public with sharing class SyncDataMaskRunLogstoPRDHandler {

    public void onAfterInsert(List<datamask__Masking_Execution_Log__c> newRunLogList, Map<Id, datamask__Masking_Execution_Log__c> newRunLogMap) {
        Organization currOrg = [Select IsSandbox from Organization limit 1];
        System.debug('SyncDataMaskRunLogstoPRDHandler > isSandbox: ' + currOrg.IsSandbox);
        if( currOrg.IsSandbox) {
            Set<String> maskExecIds = new Set<String>();
            for (datamask__Masking_Execution_Log__c log : newRunLogList) {
                if (log.datamask__Type__c == 'Execution Completion') {
                    maskExecIds.add(log.datamask__Masking_Execution_Id__c);
                }
                
                syncDataMaskRunLogstoPRD(maskExecIds);               
            }
        }
        System.debug('SyncDataMaskRunLogstoPRDHandler > complete');
    }
 
	public static void syncDataMaskRunLogstoPRD(Set<String> maskExecIds) {

        System.debug('SyncDataMaskRunLogstoPRDHandler > syncDataMaskRunLogstoPRD - start');
        
		String sandboxName = UserInfo.getUserName().substringAfterLast('.'); 
        System.debug('SyncDataMaskRunLogstoPRDHandler > syncDataMaskRunLogstoPRD - sandboxName: ' + sandboxName);
        
        List<datamask_Masking_Execution_Log_c__x> prdRunLogs = new List<datamask_Masking_Execution_Log_c__x>();
        if(maskExecIds.size() > 0) {
            List<datamask__Masking_Execution_Log__c> listLogs = [Select Id,Name, datamask__Configuration_Id__c,datamask__Configuration_Name__c,datamask__Error_Message__c,datamask__Has_Master__c,datamask__Masking_Execution_Id__c,datamask__Message__c,datamask__Object_Processing__c,datamask__Record_Count_Total__c,datamask__Records_Failed__c,datamask__Records_Processed__c,datamask__Status__c,datamask__Type__c, CreatedDate, Sandbox_Org_ID__c from datamask__Masking_Execution_Log__c where datamask__Masking_Execution_Id__c IN : maskExecIds ORDER BY CREATEDDATE];
            
            for(datamask__Masking_Execution_Log__c log : listLogs) {
                datamask_Masking_Execution_Log_c__x  prdRunLog = 
                new datamask_Masking_Execution_Log_c__x(
                    datamask_Configuration_Id_c__c = log.datamask__Configuration_Id__c,
                    datamask_Configuration_Name_c__c = log.datamask__Configuration_Name__c,
                    datamask_Error_Message_c__c = log.datamask__Error_Message__c,
                    datamask_Has_Master_c__c = log.datamask__Has_Master__c,
                    datamask_Masking_Execution_Id_c__c = log.datamask__Masking_Execution_Id__c,
                    datamask_Message_c__c = log.datamask__Message__c,
                    datamask_Object_Processing_c__c = log.datamask__Object_Processing__c,
                    datamask_Record_Count_Total_c__c = log.datamask__Record_Count_Total__c,
                    datamask_Records_Failed_c__c = log.datamask__Records_Failed__c,
                    datamask_Records_Processed_c__c = log.datamask__Records_Processed__c,
                    datamask_Status_c__c = log.datamask__Status__c,
                    datamask_Type_c__c = log.datamask__Type__c,
                    Sandbox_Org_ID_c__c = log.Sandbox_Org_ID__c,
                    Sandbox_Name_c__c = sandboxName,
                    Original_Created_Date_c__c = log.CreatedDate,
                    External_Id_c__c = log.Name
                );
                
                prdRunLogs.add(prdRunLog);
            }
            
            Database.insertAsync(prdRunLogs);
            System.debug('SyncDataMaskRunLogstoPRDHandler > syncDataMaskRunLogstoPRD - run logs inserted in prod: ' + prdRunLogs.size());
        }   

    }    
    
}